Add documentation that cloning on a network share is not supported
A user reported in #1373 that cloning failed with an exception in libgit2

  LibGit2Sharp.LibGit2SharpException: failed to create temporary file 'P:/_GIT/.git/objects/tmp_object_git2_a05280'

Investigation revealed that the clone was done on a network share.
Switching to a local path worked.

Add a remark section to clone and quick-clone to document that a local
drive should be used for cloning.

closes #1373